# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=130, null=True)),
                ('lname', models.CharField(blank=True, max_length=130, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'tblcontact',
            },
        ),
    ]
