# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
