# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_auto_20170209_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=130, null=True)),
                ('phone', models.CharField(blank=True, max_length=130, null=True)),
                ('suite', models.CharField(blank=True, max_length=130, null=True)),
                ('city', models.CharField(blank=True, max_length=130, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'tblcontact',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
