# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_auto_20170213_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
